### ISSUE TITLE
build for android compileSdkVersion - fresh Android Studio Version

### ISSUE THREAD

**Issue by lokacoding** [friyiajr/BLESampleExpo#2]
build.grandle:
  => compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '31')
 
 On Mac with fresh install of Android Studio the version 31 was not found. If I change the compileSdkVersion to 34 the sdk version error is gone but it causes following error:
  
 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

**Comment by friyiajr** [comment]
Unfortunately the compileSDKVersion and compatibility are controlled by Expo and the library maintainers. This would need to be fixed upstream by these parties.

**Comment by lokacoding** [comment]
Ah ok I found where I can install the older versions 👍
