### ISSUE TITLE
Help please with redux

### ISSUE THREAD

**Issue by renangc90** [friyiajr/BLESampleExpo#7]
Could you please check why the heartRate is not being displayed? I used your example with redux and it is not showing.

https://github.com/renangc90/bleredux

**Comment by friyiajr** [comment]
Hi, @renangc90 - regrettably I am very busy at work at the moment. I don't have spare time to debug this code. 

Since this issue also isn't related to this repo or the tutorial specifically so I am going to close it.

**Comment by renangc90** [comment]
Forgive me please, could you just tell me how I can use the heartRate by updating, for example, a useEffect in another variable? Because it shows it on the screen correctly, but it won't let me insert it into another variable

**Comment by friyiajr** [comment]
If you want the data from the heart rate monitor to be visible globally in your app you need to take advantage of the full RTK infrastructure. 

I made the `bleManager` global and have a thunk file for listening to events. You would need to structure your code closer to this like I did in the RTK video I recommended earlier. 

https://github.com/friyiajr/BleRTKSample/blob/main/src/state/BluetoothLowEnergy/listener.ts
