### ISSUE TITLE
Connect socket mobile s700 barcode scanner.

### ISSUE THREAD

**Issue by krunalshoppiko** [friyiajr/BLESampleExpo#9]
Can we connect socket mobile s700 barcode scanner and scan barcode from this device and get barcode detail?

**Comment by friyiajr** [comment]
No, its a Bluetooth Classic device and not a BLE device .

**Comment by krunalshoppiko** [comment]
have you any example for Bluetooth Classic device to connect S700?

**Comment by friyiajr** [comment]
Unfortunately, I don't have any tutorials on the subject at this time
